x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  prometheus:
    restart: "unless-stopped"
    image: prom/prometheus:latest
    user: root
    volumes:
      - prom-data:/prometheus
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME:-40d}
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-remote-write-receiver
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9090
      - metrics.instance=prometheus
      - metrics.network=${NETWORK}
      - logs.collect=true

  ethereum-metrics-exporter:
    restart: "unless-stopped"
    image: samcm/ethereum-metrics-exporter:debian-latest
    entrypoint:
      - /ethereum-metrics-exporter
      - --consensus-url=http://consensus:${CL_REST_PORT:-5052}
      - --execution-url=http://execution:${EL_RPC_PORT:-8545}
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9090
      - metrics.instance=ethereum-metrics-exporter
      - metrics.network=${NETWORK}
      - logs.collect=true

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=${NODE_EXPORTER_IGNORE_MOUNT_REGEX}'
      - '--no-collector.ipvs'
      - '--collector.textfile.directory=${NODE_EXPORTER_COLLECTOR_MOUNT_PATH:-/dev/null}'
      - '--collector.netdev.device-exclude=^(veth.*|docker.*|br-.*)$'
      - '--web.listen-address=0.0.0.0:${NODE_EXPORTER_PORT:-9199}'
    pid: host
    network_mode: host  # See all network interfaces
    restart: unless-stopped
    environment:
      - NODE_EXPORTER_COLLECTOR_MOUNT_PATH=${NODE_EXPORTER_COLLECTOR_MOUNT_PATH:-/dev/null}
    volumes:
      - /:/host:ro,rslave
      - /etc/hostname:/etc/nodename:ro
      - /proc:/host/proc:ro,rslave
      - /sys:/host/sys:ro,rslave
      - /etc/localtime:/etc/localtime:ro
      - ${NODE_EXPORTER_COLLECTOR_MOUNT_PATH:-/dev/null}:${NODE_EXPORTER_COLLECTOR_MOUNT_PATH:-/dev/null}:ro
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.host=host.docker.internal
      - metrics.port=${NODE_EXPORTER_PORT:-9199}
      - metrics.instance=node-exporter
      - metrics.network=${NETWORK}
      - logs.collect=true

  blackbox-exporter:
    restart: "unless-stopped"
    image: prom/blackbox-exporter:latest
    volumes:
      - ./prometheus/blackbox.yml:/config/blackbox.yml
      - /etc/localtime:/etc/localtime:ro
    command:
      - --config.file=/config/blackbox.yml
    <<: *logging

  json-exporter:
    restart: "unless-stopped"
    image: prometheuscommunity/json-exporter:latest
    volumes:
      - ./prometheus/json.yml:/config/json.yml
      - /etc/localtime:/etc/localtime:ro
    command:
      - --config.file
      - /config/json.yml
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=7979
      - metrics.instance=json-exporter
      - metrics.network=${NETWORK}
      - logs.collect=true

  cadvisor:
    restart: "unless-stopped"
    image: ghcr.io/google/cadvisor:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro,rslave
      - /var/run:/var/run
      - /sys:/sys:ro,rslave
      - ${DOCKER_ROOT:-/var/lib/docker}:/var/lib/docker:ro,rslave
    devices:
      - /dev/kmsg:/dev/kmsg
    privileged: true
    command:
      - --docker_only
      - --housekeeping_interval=30s
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8080
      - metrics.instance=cadvisor
      - metrics.network=${NETWORK}
      - logs.collect=true

  alloy:
    image: grafana/alloy:latest
    restart: unless-stopped
    volumes:
      - alloy-data:/var/lib/alloy
      - ./alloy:/etc/alloy
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_ROOT:-/var/lib/docker}/containers:/var/lib/docker/containers:ro,rslave
    extra_hosts:  # So we can scrape targets on the host
      - "host.docker.internal:host-gateway"
    entrypoint:
      - alloy
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=12345
      - metrics.instance=alloy
      - metrics.network=${NETWORK}
      - logs.collect=true

  loki:
    image: grafana/loki:latest
    volumes:
      - loki-data:/tmp
      - ./loki:/etc/loki
    command:
      - '--config.file=/etc/loki/loki.yml'
    restart: "unless-stopped"
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=3100
      - metrics.instance=loki
      - metrics.network=${NETWORK}
      - logs.collect=true

  tempo:
    image: grafana/tempo:2.10.3
    command:
      - '-config.file=/etc/tempo.yaml'
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/overrides.yaml:/etc/overrides.yaml
      - tempo-data:/var/tempo
    restart: "unless-stopped"
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=3200
      - metrics.instance=tempo
      - metrics.network=${NETWORK}
      - logs.collect=true

  grafana:
    restart: "unless-stopped"
    build:
      context: ./grafana
    image: grafana:local
    pull_policy: never
    user: grafana
    environment:
      - GF_SERVER_HTTP_PORT=${GRAFANA_PORT}
      - CLIENT=${COMPOSE_FILE}
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["provision.sh"]
    command: /run.sh
    <<: *logging
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=web,websecure
      - traefik.http.routers.grafana.rule=Host(`${GRAFANA_HOST}.${DOMAIN}`)
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.grafana.loadbalancer.server.port=${GRAFANA_PORT}
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=3000
      - metrics.instance=grafana
      - metrics.network=${NETWORK}
      - logs.collect=true

volumes:
  grafana-data:
  grafana-config:
  prom-data:
  loki-data:
  alloy-data:
  tempo-data:
