# Grafana for use with rootless docker
# Omits node-exporter and cadvisor. If you want them, run them on the host, then scrape
# them with custom config in ./alloy/
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  prometheus:
    restart: "unless-stopped"
    image: prom/prometheus:latest
    volumes:
      - prom-data:/prometheus
      - ./prometheus/prometheus.yml:/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
    command:
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=${PROMETHEUS_RETENTION_TIME:-40d}
      - --web.enable-remote-write-receiver
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9090
      - metrics.instance=prometheus
      - metrics.network=${NETWORK}
      - logs.collect=true

  ethereum-metrics-exporter:
    restart: "unless-stopped"
    image: samcm/ethereum-metrics-exporter:debian-latest
    entrypoint:
      - /ethereum-metrics-exporter
      - --consensus-url=http://consensus:${CL_REST_PORT:-5052}
      - --execution-url=http://execution:${EL_RPC_PORT:-8545}
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9090
      - metrics.instance=ethereum-metrics-exporter
      - metrics.network=${NETWORK}
      - logs.collect=true

  blackbox-exporter:
    restart: "unless-stopped"
    image: prom/blackbox-exporter:latest
    volumes:
      - ./prometheus/blackbox.yml:/config/blackbox.yml
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    command:
      - --config.file=/config/blackbox.yml

  json-exporter:
    restart: "unless-stopped"
    image: prometheuscommunity/json-exporter:latest
    volumes:
      - ./prometheus/json.yml:/config/json.yml
      - /etc/localtime:/etc/localtime:ro
    <<: *logging
    command:
      - --config.file
      - /config/json.yml
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=7979
      - metrics.instance=json-exporter
      - metrics.network=${NETWORK}
      - logs.collect=true

  tempo:
    image: grafana/tempo:2.10.4
    command:
      - '-config.file=/etc/tempo.yaml'
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/overrides.yaml:/etc/overrides.yaml
      - tempo-data:/var/tempo
    restart: "unless-stopped"
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=3200
      - metrics.instance=tempo
      - metrics.network=${NETWORK}
      - logs.collect=true

  alloy:
    image: grafana/alloy:latest
    restart: unless-stopped
    volumes:
      - alloy-data:/var/lib/alloy
      - ./alloy:/etc/alloy
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCK:-${XDG_RUNTIME_DIR%/}/docker.sock}:/var/run/docker.sock:ro
    extra_hosts:  # So we can scrape targets on the host
      - "host.docker.internal:host-gateway"
    entrypoint:
      - alloy
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=12345
      - metrics.instance=alloy
      - metrics.network=${NETWORK}
      - logs.collect=true

  loki:
    image: grafana/loki:latest
    volumes:
      - loki-data:/tmp
      - ./loki:/etc/loki
    command:
      - '--config.file=/etc/loki/loki.yml'
    restart: "unless-stopped"
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=3100
      - metrics.instance=loki
      - metrics.network=${NETWORK}
      - logs.collect=true

  grafana:
    restart: "unless-stopped"
    build:
      context: ./grafana
    image: grafana:local
    pull_policy: never
    user: grafana
    environment:
      - GF_SERVER_HTTP_PORT=${GRAFANA_PORT}
      - CLIENT=${COMPOSE_FILE}
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-config:/etc/grafana
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - prometheus
    entrypoint: ["provision.sh"]
    command: /run.sh
    <<: *logging
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=web,websecure
      - traefik.http.routers.grafana.rule=Host(`${GRAFANA_HOST}.${DOMAIN}`)
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.grafana.loadbalancer.server.port=${GRAFANA_PORT}

volumes:
  grafana-data:
  grafana-config:
  prom-data:
  tempo-data:
  loki-data:
  alloy-data:
