# Use ./alloy/write-loki.yml and ./alloy/write-prometheus.yml to control
# where logs and metrics are being sent
# ./alloy can have additional configuration files such as custom scrape targets
#
# This file is called grafana-cloud.yml, as adding a remote write to Grafana Cloud is a
# common use case. It properly is a Grafana Alloy without local Grafana, or a local metrics/log store


x-logging: &logging
  logging:
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ID}}'

services:
  ethereum-metrics-exporter:
    restart: "unless-stopped"
    image: samcm/ethereum-metrics-exporter:debian-latest
    entrypoint:
      - /ethereum-metrics-exporter
      - --consensus-url=http://consensus:${CL_REST_PORT:-5052}
      - --execution-url=http://execution:${EL_RPC_PORT:-8545}
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=9090
      - metrics.instance=ethereum-metrics-exporter
      - logs.collect=true

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--path.udev.data=/rootfs/run/udev/data'
      - '--collector.filesystem.mount-points-exclude=${NODE_EXPORTER_IGNORE_MOUNT_REGEX}'
      - '--collector.textfile.directory=/tmp/text-collector'
      - '--collector.netdev.device-exclude=^(veth.*|docker.*|br-.*)$'
      - '--web.listen-address=0.0.0.0:${NODE_EXPORTER_PORT:-9199}'
      - '--no-collector.ipvs'
      - '--no-collector.cpufreq'
    pid: host
    network_mode: host  # See all network interfaces
    restart: unless-stopped
    environment:
      - NODE_EXPORTER_COLLECTOR_MOUNT_PATH=${NODE_EXPORTER_COLLECTOR_MOUNT_PATH:-/dev/null}
    volumes:
      - /:/rootfs:ro,rslave
      - /sys:/host/sys:ro,rslave
      - /etc/hostname:/etc/nodename:ro
      - /etc/localtime:/etc/localtime:ro
      - ${NODE_EXPORTER_COLLECTOR_MOUNT_PATH:-/tmp/dummy-nodeexp-text}:/tmp/text-collector:ro
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.host=host.docker.internal
      - metrics.port=${NODE_EXPORTER_PORT:-9199}
      - metrics.instance=node-exporter
      - metrics.network=${NETWORK}
      - logs.collect=true

  blackbox-exporter:
    restart: "unless-stopped"
    image: prom/blackbox-exporter:latest
    volumes:
      - ./prometheus/blackbox.yml:/config/blackbox.yml
      - /etc/localtime:/etc/localtime:ro
    command:
      - --config.file=/config/blackbox.yml
    <<: *logging
    labels:
      - logs.collect=true

  json-exporter:
    restart: "unless-stopped"
    image: prometheuscommunity/json-exporter:latest
    volumes:
      - ./prometheus/json.yml:/config/json.yml
      - /etc/localtime:/etc/localtime:ro
    command:
      - --config.file
      - /config/json.yml
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=7979
      - metrics.instance=json-exporter
      - metrics.network=${NETWORK}
      - logs.collect=true

  cadvisor:
    restart: "unless-stopped"
    image: ghcr.io/google/cadvisor:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro,rslave
      - /var/run:/var/run
      - /sys:/sys:ro,rslave
      - ${DOCKER_ROOT:-/var/lib/docker}:/var/lib/docker:ro,rslave
    devices:
      - /dev/kmsg:/dev/kmsg
    privileged: true
    command:
      - --docker_only
      - --housekeeping_interval=30s
    <<: *logging
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=8080
      - metrics.instance=cadvisor
      - metrics.network=${NETWORK}
      - logs.collect=true

  alloy:
    image: grafana/alloy:latest
    restart: unless-stopped
    volumes:
      - alloy-data:/var/lib/alloy
      - ./alloy:/etc/alloy
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
    extra_hosts:  # So we can scrape targets on the host
      - "host.docker.internal:host-gateway"
    entrypoint:
      - alloy
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy
    labels:
      - metrics.scrape=true
      - metrics.path=/metrics
      - metrics.port=12345
      - metrics.instance=alloy
      - metrics.network=${NETWORK}
      - logs.collect=true

volumes:
  alloy-data:
