x-logging: &logging
  logging:
    driver: ${LOG_DRIVER}
    options:
      max-size: ${LOG_MAX_SIZE}
      max-file: ${LOG_MAX_FILE}
      tag: ${LOG_TAG}

services:
  ssv-pulse:
    image: ghcr.io/ssvlabs/ssv-pulse:latest
    pull_policy: always
    restart: no
    <<: *logging
    command:
      - 'benchmark'
      - '--consensus-addr=${CL_NODE}'
      - '--execution-addr=${EL_RPC_NODE}'
      - '--ssv-addr=http://ssv-node:16000'  # Change to your SSV Node's address with SSVAPIPort
      - '--duration=60m'
      - '--network=${NETWORK}'
      # - '--platform linux/arm64' # Add this if you run on an arm64 machine

networks:
  default:
    enable_ipv6: ${IPV6:-false}
