# To be used in conjunction with lighthouse.yml. It's meant for accessing a remote VC
# with Siren
# Please be extremely cautious when exposing your validator API port, source-firewall access
services:
  validator:
    labels:
      - traefik.enable=true
      - traefik.http.routers.${VC_HOST:-vc}.service=${VC_HOST:-vc}
      - traefik.http.routers.${VC_HOST:-vc}.entrypoints=websecure
      - traefik.http.routers.${VC_HOST:-vc}.rule=Host(`${VC_HOST:-vc}.${DOMAIN}`)
      - traefik.http.routers.${VC_HOST:-vc}.tls.certresolver=letsencrypt
      - traefik.http.services.${VC_HOST:-vc}.loadbalancer.server.port=${KEY_API_PORT:-7500}
